const RESPONSE_MESSAGES = {
    USER_CREATED: 'User created successfully.',
    USER_UPDATED: 'User updated successfully.',
    USER_DELETED: 'User deleted successfully.',
    USER_NOT_FOUND: 'User not found.',
    LOGIN_SUCCESS: 'Login successful',
    LOGIN_FAILED: 'Invalid credentials.',
    EMAIL_PASSWORD_REQUIRED:'Email and password are required',
    PASSWORD_RESET_SENT: 'A password reset link has been sent to your email.',
    PASSWORD_RESET_SUCCESS: 'Password has been reset successfully.',
    RETRIEVED:'Retrived data get successfully',
    INVALID_TOKEN: 'Invalid token.',
    INVALID_REQUEST: 'Invalid request.',
    FORBIDDEN_ACCESS: 'You do not have permission to perform this action.',
    INTERNAL_ERROR: 'An internal server error occurred.',
    EMPTY: null,
    PASSWORD_UPDATE_FAILED:'Passord update Failed',
    EMAIL_ALREADY_IN_USE: 'Email already in use',
    SERVER_ERROR: 'An error occurred while creating the user',
    EMAIL_NOT_FOUND:'EMAIL_NOT_FOUND',
    ALREADY_ASSOCIATED_ACCOUNT: 'This email or phoneNumber is associated with another account',
    ALREADY_ACCOUNT_BLOCKED: 'Account has been blocked, please talk to admin',
    INVALID_CREDENTIALS: 'Invalid credentials',
    INVALID_USER: 'Invalid user',
    INVALID_TOKEN: 'Invalid Token',
    UNVERIFIED_ACCOUNT: 'Your account has not been verified yet',
    VERIFIED_ACCOUNT: 'Account has already been verified',
    VERIFIED_EMAIL_ACCOUNT: 'Email has already been verified',
    VERIFIED_PHONE_NO_ACCOUNT: 'Phone Number has already been verified',
    PROVIDE_EMAIL: "Please provide email",
    SERVICE_NOT_AVAILABLE: "Service not available for this email",
    TERM_AND_CONDITION: "Please Agreed on Terms and Condition",
    INCORRECT_OLD_PASSWORD: "your older password is incorrect",
    INVALID_OTP: 'Invalid otp',
    INVALID_OTP_ID: 'Invalid otp ID',
    OTP_ISNT_VERIFIED: "Either otp has not been generated or verified for the reset password step",
    OTP_EXPIRED: 'Otp has been expired',
    TOKEN_DATA_RETRIEVED:'Token Data retrived successfully',
    SUCCESS: 'Success',
    INVALID_CURRENCY: 'Provided currency is not acceptable',
    INVALID_OLD_PASSWORD: 'Invalid Old password',
    INVALID_BLOG_ID: 'Blog ID not found',
    INVALID_BLOG_COMMENT_ID: 'Blog Comment ID not found',
    INVALID_FAQ_ID: 'faq ID not found',
    INVALID_TROUBLESHOOT_ID: 'troubleShoot ID not found',
    INVALID_NOTIFICATION_ID: 'Notification ID not found',
    COUNTRY_ID_NOT_FOUND: "Country Id not found",
    BUNDLE_ID_NOT_FOUND: 'Bundle ID not found',
    BUNDLE_UNAVAILABLE: "Plan you are trying to buy is currently unavailable",
    ORDER_ID_NOT_FOUND: 'Order ID not found',
    PROMO_ID_NOT_FOUND: 'Promo ID not found',
    PROMO_CODE_NOT_FOUND: 'Promo Code not found',
    ESIM_ID_NOT_FOUND: 'Esim id not found',
    MINIMUM_SPEND_CURRENCY: 'You do not qualify for minimum spend amount',
    INVENTORY_ID_NOT_FOUND: 'Inventory Id not found',
    CANT_APPLY_ESIM: "Problem in activating esim, please contact admin",
    PROVIDED_QUANTITY_IS_GEATER_THAN_PURCHASED_QUANTITY: "Provided quantity is greater than purchased quantity",
    SOME_PROBLEM_IN_GENERATING_QR: "Problem in qr generation, please request for qr on my esims sections ",
    PROMO_CODE_USAGE_LIMIT: 'You have reached the maximum limit of this promo code',
    PROMO_CODE_ALREADY_EXIST: 'Promo code already exists with this code',
    PROMO_CODE_TIMEFRAME: 'Promo code is already created for this timeframe',
    DELETE_PROMO_CODE_ALREADY_STARTED: 'Promo code cannot be deleted since it is already started',
    DELETE_PROMO_CODE_ALREADY_ENDED: 'Promo code cannot be deleted since it is already ended',
    UPDATE_PROMO_CODE_ALREADY_STARTED: 'Promo code cannot be updated since it is already started',
    UPDATE_PROMO_CODE_ALREADY_ENDED: 'Promo code cannot be updated since it is already ended',
    COUPON_CODE_ALREADY_EXIST: 'Coupon code already exists with this code',
    COUPON_ID_NOT_FOUND: 'Coupon ID not found',
    DELETE_COUPON_CODE_ALREADY_STARTED: 'Coupon code cannot be deleted since it is already started',
    DELETE_COUPON_CODE_ALREADY_ENDED: 'Coupon code cannot be deleted since it is already ended',
    UPDATE_COUPON_CODE_ALREADY_STARTED: 'Coupon code cannot be updated since it is already started',
    UPDATE_COUPON_CODE_ALREADY_ENDED: 'Coupon code cannot be updated since it is already ended',
    COUPON_CODE_USAGE_LIMIT: 'You have reached the maximum limit of this coupon code',
    EXCEEDED_WALLET_AMOUNT: "Wallet amount exceeded the total amount",
    TAB_NAME_ALREADY_TAKEN: "Tab name already taken",
    CANT_ENABLE_DOCUMENTS_ON_PLANS: "Cant enable documents on plans if country associated with it has disabled documents",
    PROVIDE_DOCUMENTS: 'Documents are mandatory for this plan',
  
    PAYMENT_FAILED: 'Payment Failed',
    INVALID_PAYMENT_ID: 'Invalid Payment ID',
    PROVIDE_DEVICE_TOKEN: "Please provide device token",
    PARTNER_WEBSITE_ID_NOT_FOUND: "Partner website Id not found",
    EMPLOYEE_ID_EXISTS: "Employee Id already exists",
    EMPLOYEE_ID_NOT_FOUND: "Employee Id not found",
  
    PARTNER_EMAIL_ERROR: "Email address not recognized. Please ensure you are registered on niyo before submitting the form.",
    PARTNER_ALREADY_CLAIMED_FREE_ESIM: "You have already claimed your eSIM",
  
    EITHER_EMAIL_HAS_SENT: "Order status should be in pending state",
    PARTNER_NOT_FOUND: "Partner not found",
  };
  
  export {
    RESPONSE_MESSAGES
  };